name: SSH on main update

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:
  remote-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Reload the relateBot server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            export NVM_DIR=\$HOME/.nvm && 
            [ -s \"\$NVM_DIR/nvm.sh\" ] && 
            . \"\$NVM_DIR/nvm.sh\" &&
            cd relateBot/ &&
            git pull &&
            pm2 status &&
            pm2 reload 0 &&
            pm2 status
          "
